// ============================================================================
// Patron Accounting — CAROUSEL painter (photo-person style), 7 slides, 1080x1350.
// Matches the "Old vs New Regime" reference deck:
//   - Navy gradient background, a Gemini-generated cutout PERSON on the right.
//   - Big bold white headline with an ORANGE HIGHLIGHT BOX on the key phrase.
//   - Optional eyebrow label (orange) + curved arrow feel via an accent rule.
//   - Optional pill checklist (rounded outline pills with a check dot).
//   - Page counter dot bottom-right ("01/07").
//   - Logo top-LEFT. NO footer text (no email/site/phone) per spec — logo only.
//
// API:
//   renderCarousel(deck) -> [Buffer per slide]
//   deck = {
//     cover: { eyebrow, headline, accent, subline, person(Image) },
//     slides:[ { n, eyebrow, headline, accent, bullets:[str], subline, person(Image) } ],
//     close: { eyebrow, headline, accent, subline, person(Image) },
//     total: 7
//   }
// The person image is a TEXT-FREE cutout-style photo generated by Gemini.
// ============================================================================
const { createCanvas } = require('@napi-rs/canvas');
const B = require('./brand');

const SIZE = B.SIZES.carousel; // 1080x1350
const NAVY = '#0a1f3d';
const NAVY2 = '#10325f';
const ORANGE = '#ff5f1b';

function navyBg(ctx, W, H) {
  const g = ctx.createLinearGradient(0, 0, W, H);
  g.addColorStop(0, '#0c2444'); g.addColorStop(0.5, NAVY); g.addColorStop(1, '#06152b');
  ctx.fillStyle = g; ctx.fillRect(0, 0, W, H);
  // soft top-left light bloom (like the ref)
  const bloom = ctx.createRadialGradient(W * 0.12, H * 0.06, 10, W * 0.12, H * 0.06, H * 0.4);
  bloom.addColorStop(0, 'rgba(255,255,255,0.16)'); bloom.addColorStop(1, 'rgba(255,255,255,0)');
  ctx.fillStyle = bloom; ctx.fillRect(0, 0, W, H);
}

// Draw the person on the right ~46% of the frame, cover-fit, anchored to bottom.
function drawPerson(ctx, img, W, H) {
  if (!img) return;
  const pw = Math.round(W * 0.52);
  const px = W - pw;
  // cover-fit into right column, bottom-aligned
  const ir = img.width / img.height;
  const tr = pw / H;
  let sx, sy, sw, sh;
  if (ir > tr) { sh = img.height; sw = sh * tr; sx = (img.width - sw) / 2; sy = 0; }
  else { sw = img.width; sh = sw / tr; sx = 0; sy = img.height - sh; }
  ctx.drawImage(img, sx, sy, sw, sh, px, 0, pw, H);
  // subtle navy gradient on the person's left edge so headline text blends
  const g = ctx.createLinearGradient(px, 0, px + pw * 0.45, 0);
  g.addColorStop(0, 'rgba(10,31,61,0.92)'); g.addColorStop(1, 'rgba(10,31,61,0)');
  ctx.fillStyle = g; ctx.fillRect(px, 0, pw * 0.5, H);
}

async function logoTL(ctx, W) {
  const lw = Math.round(W * 0.16), lh = Math.round(lw * 0.552);
  await B.drawLogo(ctx, { x: Math.round(W * 0.05), y: Math.round(W * 0.04), w: lw, h: lh, dark: true });
}

// Page counter dot bottom-right: "01/07"
function pageCounter(ctx, W, H, n, total) {
  ctx.save();
  const txt = String(n).padStart(2, '0') + '/' + String(total).padStart(2, '0');
  ctx.font = `${Math.round(W * 0.034)}px PatronDisplay`;
  ctx.textBaseline = 'middle'; ctx.textAlign = 'right';
  const y = H - Math.round(H * 0.045);
  // dot
  ctx.fillStyle = ORANGE;
  ctx.beginPath(); ctx.arc(W - ctx.measureText(txt).width - Math.round(W * 0.075), y, W * 0.012, 0, Math.PI * 2); ctx.fill();
  ctx.fillStyle = '#fff';
  ctx.fillText(txt, W - Math.round(W * 0.05), y);
  ctx.restore();
}

function eyebrow(ctx, text, x, y, W) {
  if (!text) return y;
  ctx.save();
  ctx.font = `${Math.round(W * 0.032)}px PatronDisplay`;
  ctx.fillStyle = ORANGE; ctx.textBaseline = 'alphabetic';
  ctx.fillText(text.toUpperCase(), x, y);
  ctx.restore();
  return y + Math.round(W * 0.02);
}

// Headline with one phrase wrapped in an orange highlight box.
// Words are laid out wrapped; words in `accent` get a solid orange box behind them.
function headlineWithBox(ctx, headline, accent, x, y, maxW, fontPx, lineH) {
  ctx.save();
  ctx.font = `${fontPx}px PatronDisplay`;
  ctx.textBaseline = 'alphabetic';
  const accSet = new Set(String(accent || '').toUpperCase().split(/\s+/).filter(Boolean));
  const words = String(headline || '').split(/\s+/).filter(Boolean);
  const space = ctx.measureText(' ').width;
  const padX = fontPx * 0.16, padY = fontPx * 0.12;
  let cx = x, cy = y;
  for (const w of words) {
    const ww = ctx.measureText(w).width;
    if (cx + ww > x + maxW && cx > x) { cx = x; cy += lineH; }
    const clean = w.replace(/[^A-Za-z0-9]/g, '').toUpperCase();
    if (accSet.has(clean)) {
      // orange box behind the accent word
      ctx.fillStyle = ORANGE;
      ctx.fillRect(cx - padX, cy - fontPx + padY * 0.4, ww + padX * 2, fontPx + padY);
      ctx.fillStyle = '#fff';
    } else {
      ctx.fillStyle = '#fff';
    }
    ctx.fillText(w, cx, cy);
    cx += ww + space + (accSet.has(clean) ? padX : 0);
  }
  ctx.restore();
  return cy;
}

// Outline pill checklist (rounded pill + orange check dot + label).
function pillChecklist(ctx, items, x, y, W) {
  if (!items || !items.length) return y;
  ctx.save();
  const fs = Math.round(W * 0.032);
  const ph = Math.round(fs * 2.1);
  const pad = Math.round(fs * 0.7);
  ctx.font = `${fs}px PatronMedium`;
  let cy = y;
  for (const it of items) {
    const label = String(it);
    const tw = ctx.measureText(label).width;
    const pw = pad + ph * 0.8 + tw + pad;
    // pill outline
    ctx.strokeStyle = 'rgba(255,255,255,0.4)'; ctx.lineWidth = 2;
    roundRect(ctx, x, cy, pw, ph, ph / 2); ctx.stroke();
    // check dot
    ctx.fillStyle = ORANGE;
    ctx.beginPath(); ctx.arc(x + pad + ph * 0.3, cy + ph / 2, ph * 0.28, 0, Math.PI * 2); ctx.fill();
    ctx.strokeStyle = '#fff'; ctx.lineWidth = 2.5; ctx.lineCap = 'round';
    const cxx = x + pad + ph * 0.3, cyy = cy + ph / 2, r = ph * 0.13;
    ctx.beginPath(); ctx.moveTo(cxx - r, cyy); ctx.lineTo(cxx - r * 0.2, cyy + r); ctx.lineTo(cxx + r, cyy - r); ctx.stroke();
    // label
    ctx.fillStyle = '#fff'; ctx.textBaseline = 'middle';
    ctx.fillText(label, x + pad + ph * 0.8, cy + ph / 2 + 1);
    cy += ph + Math.round(fs * 0.5);
  }
  ctx.restore();
  return cy;
}

function subline(ctx, text, x, y, maxW, W) {
  if (!text) return y;
  ctx.save();
  // small orange rule above
  ctx.fillStyle = ORANGE; ctx.fillRect(x, y, Math.round(W * 0.08), 4);
  const fs = Math.round(W * 0.034);
  const after = B.drawWrapped(ctx, text, x, y + Math.round(fs * 1.4), maxW, Math.round(fs * 1.3),
    { font: `${fs}px PatronMedium`, color: '#cfd8e6' });
  ctx.restore();
  return after;
}

function roundRect(ctx, x, y, w, h, r) {
  ctx.beginPath(); ctx.moveTo(x + r, y);
  ctx.arcTo(x + w, y, x + w, y + h, r); ctx.arcTo(x + w, y + h, x, y + h, r);
  ctx.arcTo(x, y + h, x, y, r); ctx.arcTo(x, y, x + w, y, r); ctx.closePath();
}

// ---- slide builders ---------------------------------------------------------
async function paintSlide(s, n, total) {
  const { w: W, h: H } = SIZE;
  const c = createCanvas(W, H); const ctx = c.getContext('2d');
  navyBg(ctx, W, H);
  drawPerson(ctx, s.person, W, H);
  await logoTL(ctx, W);

  const x = Math.round(W * 0.05);
  const colW = Math.round(W * 0.58);
  let y = Math.round(H * 0.2);
  y = eyebrow(ctx, s.eyebrow, x, y, W);

  const hlPx = Math.round(W * 0.085);
  y = headlineWithBox(ctx, s.headline, s.accent, x, y + hlPx, colW, hlPx, Math.round(hlPx * 1.18));
  y += Math.round(hlPx * 0.5);

  if (s.bullets && s.bullets.length) {
    y = pillChecklist(ctx, s.bullets, x, y, W);
    y += Math.round(H * 0.01);
  }
  if (s.subline) subline(ctx, s.subline, x, y, colW, W);

  pageCounter(ctx, W, H, n, total);
  return c.toBuffer('image/png');
}

async function renderCarousel(deck) {
  const total = deck.total || ((deck.slides ? deck.slides.length : 0) + (deck.cover ? 1 : 0) + (deck.close ? 1 : 0));
  const out = [];
  let n = 1;
  if (deck.cover) { out.push(await paintSlide(deck.cover, n++, total)); }
  for (const s of (deck.slides || [])) { out.push(await paintSlide(s, n++, total)); }
  if (deck.close) { out.push(await paintSlide(deck.close, n++, total)); }
  return out;
}

module.exports = { renderCarousel, paintSlide };
